# Generated by Django 4.0.5 on 2022-06-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_remove_task_team_members_task_task_memebers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="task_memebers",
            new_name="task_members",
        ),
    ]
